name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
      - uses: "node20"
        with:
          node-version: 20
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install
      - name: Build frontend
        working-directory: frontend
        run: npm run build

  backend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
      - uses: "node20"
        with:
          node-version: 20
      - name: Install backend dependencies
        working-directory: backend
        run: npm install
      - name: Test backend
        working-directory: backend
        run: npm test
